<?php

namespace WpAddon\Services;

class PageCacheNginxService
{
    public function sync(string $cacheDirectory, string $cacheUrlPath, int $ttl): bool
    {
        $directory = rtrim($cacheDirectory, '/\\').'/';
        if (! is_dir($directory) && ! wp_mkdir_p($directory)) {
            return false;
        }

        $temporaryFile = tempnam($directory, '.nginx-page-cache-');
        if ($temporaryFile === false || file_put_contents($temporaryFile, $this->buildConfig($cacheUrlPath, $ttl), LOCK_EX) === false) {
            return false;
        }

        if (! rename($temporaryFile, $directory.'nginx.conf')) {
            @unlink($temporaryFile);

            return false;
        }

        @chmod($directory.'nginx.conf', 0644);

        return true;
    }

    public function buildConfig(string $cacheUrlPath, int $ttl): string
    {
        $cacheUrlPath = '/'.trim($cacheUrlPath, '/');
        $maxAge = max(1, $ttl);

        return <<<NGINX
# Generated by WP Addon. Include inside the HTTPS `server` block.
# This replaces the existing `location /` block.
set \$wp_addon_cache_uri "{$cacheUrlPath}/\$host\$uri/index.html";
if (\$uri = /) { set \$wp_addon_cache_uri "{$cacheUrlPath}/\$host/index.html"; }
if (\$request_method !~ ^(GET|HEAD)$) { set \$wp_addon_cache_uri "/__wp_addon_cache_bypass__"; }
if (\$query_string != "") { set \$wp_addon_cache_uri "/__wp_addon_cache_bypass__"; }
if (\$http_cookie ~* "(?:wordpress_logged_in_|wp-postpass_|comment_author_|woocommerce_items_in_cart|woocommerce_cart_hash|wp_woocommerce_session_)") { set \$wp_addon_cache_uri "/__wp_addon_cache_bypass__"; }

location / {
    try_files \$wp_addon_cache_uri \$uri \$uri/ /index.php?\$args;
}

location ~* ^{$cacheUrlPath}/.+/index\.html$ {
    internal;
    gzip_static on;
    gunzip on;
    default_type text/html;
    add_header X-Page-Cache HIT always;
    add_header Cache-Control "public, max-age={$maxAge}" always;
    add_header Vary "Accept-Encoding, Cookie" always;
}
NGINX;
    }
}
