<?php

$enabledDependency = ['antispam_enabled', '==', 'true'];

return [
    [
        'id' => 'antispam_enabled',
        'type' => 'switcher',
        'title' => __('Enable comment spam protection', 'wp-addon'),
        'desc' => __('Main switch of the module. Blocked comments are rejected before they reach the database: nothing is stored, no notification email is sent, and the page cache is not purged. Replaces the Kama SpamBlock plugin.', 'wp-addon'),
        'default' => true,
    ],
    [
        'id' => 'antispam_threshold',
        'type' => 'number',
        'title' => __('Scoring threshold', 'wp-addon'),
        'desc' => __('A comment is blocked when the sum of the heuristic weights reaches this value. Higher is safer for real readers, lower catches more bots. <strong>3</strong> is the recommended balance.', 'wp-addon'),
        'default' => 3,
        'min' => 1,
        'max' => 10,
        'step' => 1,
        'dependency' => $enabledDependency,
    ],
    [
        'id' => 'antispam_honeypot',
        'type' => 'switcher',
        'title' => __('Honeypot field', 'wp-addon'),
        'desc' => __('Adds a hidden field to the comment form. Browsers and password managers fill nothing there, static bots fill everything. JavaScript removes the field before submit, so a filled field means a bot.', 'wp-addon'),
        'default' => true,
        'dependency' => $enabledDependency,
    ],
    [
        'id' => 'antispam_min_seconds',
        'type' => 'number',
        'title' => __('Minimum time on page (seconds)', 'wp-addon'),
        'desc' => __('Rejects a comment submitted faster than this value. The timestamp is written by JavaScript at page load, so the page cache does not break it. Set to 0 to disable.', 'wp-addon'),
        'default' => 3,
        'min' => 0,
        'max' => 3600,
        'step' => 1,
        'dependency' => $enabledDependency,
    ],
    [
        'id' => 'antispam_rate_hour',
        'type' => 'number',
        'title' => __('Max comments per hour from one IP', 'wp-addon'),
        'desc' => __('Sliding window limit per IP address. Disabled by default: family and office IPs legitimately comment several times in a row. Set to 0 to keep it off.', 'wp-addon'),
        'default' => 0,
        'min' => 0,
        'max' => 100,
        'step' => 1,
        'dependency' => $enabledDependency,
    ],
    [
        'id' => 'antispam_rate_day',
        'type' => 'number',
        'title' => __('Max comments per day from one IP', 'wp-addon'),
        'desc' => __('Daily sliding window limit per IP address. Disabled by default. Set to 0 to keep it off.', 'wp-addon'),
        'default' => 0,
        'min' => 0,
        'max' => 1000,
        'step' => 1,
        'dependency' => $enabledDependency,
    ],
    [
        'id' => 'antispam_check_backlinks',
        'type' => 'switcher',
        'title' => __('Verify pingback and trackback sources', 'wp-addon'),
        'desc' => __('Fetches the page that sent the pingback and requires a real link to this site in it. Same check as in Kama SpamBlock.', 'wp-addon'),
        'default' => true,
        'dependency' => $enabledDependency,
    ],
    [
        'id' => 'antispam_trust_moderators',
        'type' => 'switcher',
        'title' => __('Trust users who can moderate comments', 'wp-addon'),
        'desc' => __('Administrators and editors never pass through the checks, so a real person replying from the admin panel cannot be blocked.', 'wp-addon'),
        'default' => true,
        'dependency' => $enabledDependency,
    ],
    [
        'id' => 'antispam_blocked_message',
        'type' => 'textarea',
        'title' => __('Rejected message', 'wp-addon'),
        'desc' => __('Shown on the WordPress "Comment Submission Failure" page. Keep it friendly: bots ignore it, readers may see it by accident.', 'wp-addon'),
        'default' => 'Your comment looks like spam and was rejected. Please review it and try again.',
        'dependency' => $enabledDependency,
    ],
    [
        'id' => 'antispam_stats',
        'type' => 'content',
        'content' => is_admin() && class_exists('CommentAntispam') ? CommentAntispam::renderAdminPanel() : '',
        'dependency' => $enabledDependency,
    ],
];
